from __future__ import annotations

from typing import Any, Protocol

import httpx

from app.core.config import (
    CONTENT_PROVIDER,
    EXA_API_KEY,
    EXA_CONTENTS_URL,
    EXA_TEXT_MAX_CHARACTERS,
    EXA_TIMEOUT_SECONDS,
)


class PageReaderProtocol(Protocol):
    def fetch(self, url: str, published_before: str | None = None) -> dict:
        ...


class PageReader:
    """
    Local placeholder reader used by tests and API-key-free development.
    """

    def fetch(self, url: str, published_before: str | None = None) -> dict:
        return {
            "url": url,
            "title": url.rsplit("/", 1)[-1].replace("-", " ").title(),
            "published_at": published_before or "",
            "content_summary": (
                "This source was generated by the local placeholder reader. "
                "It provides a stable observation payload for orchestration and tests."
            ),
            "raw": {},
        }


class ExaPageReader:
    def __init__(self, api_key: str = EXA_API_KEY) -> None:
        if not api_key:
            raise ValueError("EXA_API_KEY is required when FORECAST_CONTENT_PROVIDER=exa.")
        self.api_key = api_key

    def fetch(self, url: str, published_before: str | None = None) -> dict:
        payload: dict[str, Any] = {
            "urls": [url],
            "text": {"maxCharacters": EXA_TEXT_MAX_CHARACTERS},
            "highlights": {"numSentences": 3},
        }
        response = httpx.post(
            EXA_CONTENTS_URL,
            headers={"x-api-key": self.api_key, "Content-Type": "application/json"},
            json=payload,
            timeout=EXA_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        results = response.json().get("results", [])
        if not results:
            return {
                "url": url,
                "title": url.rsplit("/", 1)[-1],
                "published_at": published_before or "",
                "content_summary": "",
                "raw": {},
            }
        item = results[0]
        highlights = item.get("highlights") or []
        text = item.get("text") or ""
        summary = " ".join(str(part) for part in highlights if part) or text[:EXA_TEXT_MAX_CHARACTERS]
        return {
            "url": item.get("url") or url,
            "title": item.get("title") or url.rsplit("/", 1)[-1],
            "published_at": item.get("publishedDate") or published_before or "",
            "content_summary": summary,
            "raw": item,
        }


def create_page_reader(provider_name: str = CONTENT_PROVIDER) -> PageReaderProtocol:
    if provider_name == "exa":
        return ExaPageReader()
    if provider_name in {"synthetic", "local", ""}:
        return PageReader()
    raise ValueError(f"Unsupported content provider: {provider_name}")
